#!/usr/bin/env node

require('shelljs/global');
VERSION = process.argv[2]
var util            = require('util')
,   exec            = require('child_process').exec
,   fs              = require('fs')
,	oldVer          = process.argv[3];


mkdir('-p', 'Release');

